language: node_js
node_js:
  - "10"
dist: trusty
sudo: false
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test